[package]
name = "privy-cloud-desktop"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
reqwest = { version = "0.12", default-features = false, features = ["json", "blocking"] }
serde_json = "1"

[lib]
name = "privy_cloud_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
